trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/heads/avoid/gitversion
      endpoint: github

variables:
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '7dfeb756-b27e-47ec-8906-a349cf7e0688'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      GithubAuthVariableGroup: rsg-bot
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: true
      DotNetSdk:
        - "2.2.x"
        - "3.0.x"
      NuGetVersion: "5.2.0"
